
#General settings
[general]
	#Apply Mod On...
	#0 = Nothing (why install the mod though?)
	#1 = Llamas
	#2 = Trader Llamas
	#3 = Both
	#Range: 0 ~ 3
	applyOn = 3
	#Chance of llamas wearing parts of their outfit, in percentage% (0-100)
	#Range: 0 ~ 100
	fancyChance = 80

#Settings regarding llamas that are wearing outfits
[outfit]
	#Chance of llamas wearing hats in their outfit, in percentage% (0-100)
	#Range: 0 ~ 100
	hatChance = 100
	#Chance of llamas wearing a monocle in their outfit, in percentage% (0-100)
	#Range: 0 ~ 100
	monocleChance = 100
	#Chance of llamas having a pipe in their outfit, in percentage% (0-100)
	#Range: 0 ~ 100
	pipeChance = 100
	#Chance of llamas wearing a bow tie in their outfit, in percentage% (0-100)
	#Range: 0 ~ 100
	bowtieChance = 100
	#Chance of llamas wearing a fez in their outfit, in percentage% (0-100)
	#Range: 0 ~ 100
	fezChance = 100
	#Chance of llamas wearing a moustache in their outfit, in percentage% (0-100)
	#Range: 0 ~ 100
	moustacheChance = 100

