
[core]

	[core.general]
		#If an anonymous mod startup analytics request may be sent to our analytics service.
		analytics = true
		#If the version checker should be enabled.
		versionChecker = true
		#Maximum buffer byte size for adaptive inventory slots fragmentation.
		maxPacketBufferSize = 20000
		#If the recipe loader should crash when finding invalid recipes.
		crashOnInvalidRecipe = false
		#If mod compatibility loader should crash hard if errors occur in that process.
		crashOnModCompatCrash = false

[general]

	[general.general]
		#Always create full creative-mode chests when formed. Should not be used in survival worlds!
		creativeChests = false
		#If the higher tier metal variants can be crafted.
		metalVariants = true
		#If the interface input overlay should always be rendered on chests.
		alwaysShowInterfaceOverlay = true
		#If items should be ejected from the chests if one of the structure blocks are removed.
		ejectItemsOnDestroy = false

	[general.colossal_chest]
		#If the chest should visually open when someone uses it.
		chestAnimation = true

[machine]

	[machine.colossal_chest]
		#The maximum size a colossal chest can have.
		maxSize = 20

