
[oregen]
	#Generate Runestone
	generateRunestone = true
	#Maximum Arcane Crystal Ore veins per chunk
	#Range: 1 ~ 10000000
	ArcaneCrystalOreCount = 3
	#Maximum Dark Stone veins per chunk
	#Range: 1 ~ 10000000
	DarkStoneCount = 20
	#Maximum height for the Dark Runestone
	#Range: 1 ~ 256
	DarkRunestoneMaxHeight = 9
	#Minimum height for the Dark Stone
	#Range: 1 ~ 256
	DarkStoneMinHeight = 1
	#Generate Arcane Crystal Ore
	generateArcaneCrystalOre = true
	#Maximum height for the Arcane Crystal Ore
	#Range: 1 ~ 256
	ArcaneCrystalOreMaxHeight = 20
	#Maximum Dark Runestone veins per chunk
	#Range: 1 ~ 10000000
	DarkRunestoneCount = 3
	#Generate Dark Runestone
	generateDarkRunestone = true
	#Generate Dark Stone
	generateDarkStone = true
	#Maximum Runestone veins per chunk
	#Range: 1 ~ 10000000
	RunestoneCount = 3
	#Maximum size of Arcane Crystal Ore vein
	#Range: 0 ~ 500
	maxArcaneCrystalOreVeinSize = 6
	#Maximum height for the Runestone
	#Range: 1 ~ 256
	RunestoneMaxHeight = 25
	#Minimum height for the Runestone
	#Range: 1 ~ 256
	RunestoneMinHeight = 1
	#Maximum size of Dark Stone vein
	#Range: 0 ~ 500
	maxDarkStoneVeinSize = 20
	#Maximum size of Runestone vein
	#Range: 0 ~ 500
	maxRunestoneVeinSize = 3
	#Maximum height for the Dark Stone
	#Range: 1 ~ 256
	DarkStoneMaxHeight = 8
	#Maximum size of Dark Runestone vein
	#Range: 0 ~ 500
	maxDarkRunestoneVeinSize = 3
	#Minimum height for the Arcane Crystal Ore
	#Range: 1 ~ 256
	ArcaneCrystalOreMinHeight = 1
	#Minimum height for the Dark Runestone
	#Range: 1 ~ 256
	DarkRunestoneMinHeight = 1

