#The amount of slots each sorting interface should check for changes per tick. Setting this too high while having many interfaces on large inventories can cause performance issues.
sortingInterfaceSlotsPerTick = 9

